version: '3'
services:
  db:
    image: mysql
    container_name: ${DATABASE_HOST}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_HOST: ${DATABASE_HOST}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports: 
      - 3306:3306
    volumes:
      - ./init.sql:/data/application/init.sql
  php-fpm:
    build:
      context: docker/php-fpm
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ./Backend/Smart-Doctrina:/var/www
    ports:
      - 9000:9000
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./Backend/Smart-Doctrina:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - 80:80
  node:
    build:
      context: Backend/Smart-Auth/
      dockerfile: ../../docker/node/dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
        - 8081:8081
    volumes:
      - ./Backend/Smart-Auth:/usr/src/app

  angular:
    build:
      context: Frontend/
      dockerfile: ../docker/angular/dockerfile
    depends_on:
      - node
    ports:
        - 4200:4200
    volumes:
      - ./Frontend:/usr/src/app